apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
