apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices
  namespace: argocd
spec:
  description: Microservices Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    # Any other namespace or server is fine though.
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
