apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/MallikarjunaReddyN/kind-kubernetes-argocd-istio.git
    targetRevision: main
    path: argo-applications/microservices-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
